// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbxdmI3EoNT_QtOD6Hl59nUXRV9p0yFY',
    appId: '1:763343686794:web:5173c42c4062aa270d7173',
    messagingSenderId: '763343686794',
    projectId: 'reddit-clone-tutorial-b5160',
    authDomain: 'reddit-clone-tutorial-b5160.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-b5160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeHGHpvlc9pQjRgeiPTcWUHP9IfN-O8Q',
    appId: '1:763343686794:android:3e50f02fb57347e70d7173',
    messagingSenderId: '763343686794',
    projectId: 'reddit-clone-tutorial-b5160',
    storageBucket: 'reddit-clone-tutorial-b5160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA3hCbORkg7i0ZxVIikRoMGDD4Li-1Q6M',
    appId: '1:763343686794:ios:faa044ed85f34c0d0d7173',
    messagingSenderId: '763343686794',
    projectId: 'reddit-clone-tutorial-b5160',
    storageBucket: 'reddit-clone-tutorial-b5160.appspot.com',
    iosClientId: '763343686794-icfbu83pue0pqqg8mdir2g9sok8ibrpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA3hCbORkg7i0ZxVIikRoMGDD4Li-1Q6M',
    appId: '1:763343686794:ios:faa044ed85f34c0d0d7173',
    messagingSenderId: '763343686794',
    projectId: 'reddit-clone-tutorial-b5160',
    storageBucket: 'reddit-clone-tutorial-b5160.appspot.com',
    iosClientId: '763343686794-icfbu83pue0pqqg8mdir2g9sok8ibrpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
